import { AppContextProvider } from "@/components/app-context"
import { NavBar } from "@/components/navbar"
import { SideBar } from "@/components/sidebar"
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark
            }}
        >
            <html lang="en">
                <body className={inter.className}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <AppContextProvider>
                            <div className="grid-cols-10 md:grid">
                                <SideBar className="col-span-2 h-screen bg-accent/50" />
                                <div className="col-span-8 px-8">
                                    <NavBar />
                                    <div className="w-full">{children}</div>
                                </div>
                            </div>
                        </AppContextProvider>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
